Unitech scanner implementation
icapps/combined_barcode_scanner pull request #1
Opened 2022-01-05 12:06 UTC by NicolaVerbeeck

2022-01-05 13:18 UTC, vanlooverenkoen requested changes

2022-01-05 13:18 UTC, vanlooverenkoen commented on pkgs/unitech/README.md
> +
Also add a simple example. We should also specify that combined_barcode_scanner is required as well
```
BarcodeScannerWidget(
        controller: _controller,
        onScan: (code) {
          if (kDebugMode) {
            print("GOT BARCODE =========== ${code.code}");
          }
        },
        configuration: const ScannerConfiguration(
          enableFormats: {BarcodeFormat.qr},
        ),
        scanners: [UnitechBarcodeScanner()],
      ),
```

2022-01-05 13:18 UTC, vanlooverenkoen commented on pkgs/unitech/android/src/main/kotlin/com/icapps/unitech_scanner/UnitechScannerPlugin.kt
> +                val barcodeStr = bundle.getString("text")
in this bundle we can't find the type of barcode/qrcode was scanned?

2022-01-05 15:35 UTC, NicolaVerbeeck commented
PR comments fixed in other PR 🤦

2022-01-07 09:26 UTC, vanlooverenkoen approved these changes

2022-01-07 10:45 UTC, merged